import type { Part } from '../models/Part'
import type { Sheet } from '../models/Sheet'
import { formatNumber } from './format'
import { transformLocalPoint, transformPartProgram } from './transform'

export interface ExportResult {
  gcode: string
  errors: string[]
  warnings: string[]
}

export function exportCombinedGCode(parts: Part[], sheet: Sheet): ExportResult {
  const errors: string[] = []
  const warnings: string[] = []
  const output: string[] = []

  output.push('(Combined CNC job generated by Sheet Builder)')
  output.push(`(Sheet: ${formatNumber(sheet.width)} x ${formatNumber(sheet.height)} mm)`)
  output.push(...sheet.gcodeSettings.startGcode.split('\n').filter(Boolean))

  for (const [index, instance] of sheet.instances.entries()) {
    const part = parts.find((candidate) => candidate.id === instance.partId)
    if (!part) {
      errors.push(`Instance ${instance.id} references a missing library part.`)
      continue
    }

    const firstPoint = transformLocalPoint(part, instance, { x: part.originalBounds.minX, y: part.originalBounds.minY })
    output.push('')
    output.push(`(Part: ${part.name})`)
    output.push(`(Instance: ${index + 1} / ${instance.id})`)
    output.push(`(Position: X${formatNumber(instance.x)} Y${formatNumber(instance.y)})`)
    output.push(`(Rotation: ${instance.rotation})`)
    output.push(`G00 Z${formatNumber(sheet.gcodeSettings.safeZ)}`)
    output.push(`G00 X${formatNumber(firstPoint.x)} Y${formatNumber(firstPoint.y)}`)

    const transformed = transformPartProgram(part, instance)
    errors.push(...transformed.errors)
    warnings.push(...transformed.warnings)
    output.push(...transformed.lines)
  }

  output.push('')
  output.push(`G00 Z${formatNumber(sheet.gcodeSettings.safeZ)}`)
  output.push(...sheet.gcodeSettings.endGcode.split('\n').filter(Boolean))

  return { gcode: `${output.join('\n')}\n`, errors, warnings: Array.from(new Set(warnings)) }
}
