import type { Part } from '../models/Part'
import type { Sheet } from '../models/Sheet'
import { formatNumber } from './format'
import { wordsToLine } from './format'
import { transformLocalPoint, transformPartProgram } from './transform'
import type { ParsedLine } from './types'

export interface ExportResult {
  gcode: string
  errors: string[]
  warnings: string[]
}

function lineWithXyFeedOverride(line: ParsedLine, feedRate?: number): string {
  if (!feedRate || feedRate <= 0) return line.raw
  const motion = line.effectiveMotion
  const hasXy = line.words.some((word) => word.letter === 'X' || word.letter === 'Y')
  if (!hasXy || motion === 'G00') return line.raw
  if (motion !== 'G01' && motion !== 'G02' && motion !== 'G03') return line.raw

  const feedIndex = line.words.findIndex((word) => word.letter === 'F')
  const words = [...line.words]
  const feedWord = { letter: 'F', value: feedRate, raw: `F${formatNumber(feedRate)}` }
  if (feedIndex >= 0) words[feedIndex] = feedWord
  else words.push(feedWord)

  return wordsToLine(words, line.comment)
}

export function exportCombinedGCode(parts: Part[], sheet: Sheet): ExportResult {
  const errors: string[] = []
  const warnings: string[] = []
  const output: string[] = []

  output.push('(Combined CNC job generated by Sheet Builder)')
  output.push(`(Sheet: ${formatNumber(sheet.width)} x ${formatNumber(sheet.height)} mm)`)
  output.push(...sheet.gcodeSettings.startGcode.split('\n').filter(Boolean))
  const xyFeedRateMmPerMinute = sheet.gcodeSettings.xyFeedRateMmPerSecond
    ? sheet.gcodeSettings.xyFeedRateMmPerSecond * 60
    : undefined

  for (const [index, instance] of sheet.instances.entries()) {
    const part = parts.find((candidate) => candidate.id === instance.partId)
    if (!part) {
      errors.push(`Instance ${instance.id} references a missing library part.`)
      continue
    }

    const firstPoint = transformLocalPoint(part, instance, { x: part.originalBounds.minX, y: part.originalBounds.minY })
    output.push('')
    output.push(`(Part: ${part.name})`)
    output.push(`(Instance: ${index + 1} / ${instance.id})`)
    output.push(`(Position: X${formatNumber(instance.x)} Y${formatNumber(instance.y)})`)
    output.push(`(Rotation: ${instance.rotation})`)
    output.push(`G00 Z${formatNumber(sheet.gcodeSettings.safeZ)}`)
    output.push(`G00 X${formatNumber(firstPoint.x)} Y${formatNumber(firstPoint.y)}`)

    const transformed = transformPartProgram(part, instance)
    errors.push(...transformed.errors)
    warnings.push(...transformed.warnings)
    if (sheet.gcodeSettings.applyXyFeedRate) {
      warnings.push(
        `Applied XY feed override ${formatNumber(sheet.gcodeSettings.xyFeedRateMmPerSecond ?? 0)} mm/s as F${formatNumber(xyFeedRateMmPerMinute ?? 0)} mm/min.`,
      )
      output.push(...transformed.transformedLines.map((line) => lineWithXyFeedOverride(line, xyFeedRateMmPerMinute)))
    } else {
      output.push(...transformed.lines)
    }
  }

  output.push('')
  output.push(`G00 Z${formatNumber(sheet.gcodeSettings.safeZ)}`)
  output.push(...sheet.gcodeSettings.endGcode.split('\n').filter(Boolean))

  return { gcode: `${output.join('\n')}\n`, errors, warnings: Array.from(new Set(warnings)) }
}
